name: myapp
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: "^2.12.0"

dependencies:
  json_annotation: "^4.0.0"
  http: "^0.13.0"
  fl_chart: "^0.20.1"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^1.11.5"
  json_serializable: "^4.0.2"

flutter:
  uses-material-design: true